// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDIAvUe7FUvRKM9TUqPfIyW33tkLsPc0',
    appId: '1:491813756299:web:93af2b4d75f6b229fce38e',
    messagingSenderId: '491813756299',
    projectId: 'flutter-registration-f361c',
    authDomain: 'flutter-registration-f361c.firebaseapp.com',
    storageBucket: 'flutter-registration-f361c.firebasestorage.app',
    measurementId: 'G-RR7WNNH4CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHT0_G_gi22zjmZja3m6GAwNhezkO0G8',
    appId: '1:491813756299:android:225099784f1f9f20fce38e',
    messagingSenderId: '491813756299',
    projectId: 'flutter-registration-f361c',
    storageBucket: 'flutter-registration-f361c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbW0IJyKWQZX0j2Aga2Y1nzRPJrSpTXBk',
    appId: '1:491813756299:ios:25607c9c5b10d06bfce38e',
    messagingSenderId: '491813756299',
    projectId: 'flutter-registration-f361c',
    storageBucket: 'flutter-registration-f361c.firebasestorage.app',
    iosBundleId: 'com.example.flutterRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbW0IJyKWQZX0j2Aga2Y1nzRPJrSpTXBk',
    appId: '1:491813756299:ios:25607c9c5b10d06bfce38e',
    messagingSenderId: '491813756299',
    projectId: 'flutter-registration-f361c',
    storageBucket: 'flutter-registration-f361c.firebasestorage.app',
    iosBundleId: 'com.example.flutterRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDIAvUe7FUvRKM9TUqPfIyW33tkLsPc0',
    appId: '1:491813756299:web:ccf9db4b52c0e23ffce38e',
    messagingSenderId: '491813756299',
    projectId: 'flutter-registration-f361c',
    authDomain: 'flutter-registration-f361c.firebaseapp.com',
    storageBucket: 'flutter-registration-f361c.firebasestorage.app',
    measurementId: 'G-ZC3CLHR90L',
  );
}
